# This script harmonizes and de-duplicates multiple studies from the ADKP,
# filling in missing information where there is sample overlap between a data
# set and the Diverse Cohorts / AMP-AD 1.0 / NPS-AD data. Harmonized metadata is
# uploaded to Synapse for use.
#
# The following data sets are harmonized in this script:
#   MC-BrAD
#   MC_snRNA
#   MCMPS
#   SEA-AD
#   SMIB-AD

library(synapser)
library(dplyr)
library(purrr)
library(stringr)
library(readxl)

source("util_functions.R")
source("harmonize_function.R")

studies <- config::get("studies")
spec <- config::get("columns")

# TRUE will print column names of metadata + unique values for each dataset.
# FALSE will only print the status of the harmonized metadata for each dataset.
verbose <- FALSE

# Assume this file has been generated by Step 1.
harmonized_baseline <- readRDS(file.path("data", "tmp", "AMP1.0_DiverseCohorts_harmonized.rds"))

synLogin(silent = TRUE)
upload_id <- config::get("upload_synID")


# MC-BrAD ----------------------------------------------------------------------

# Has some sample overlap with AMP-AD 1.0 Mayo metadata and Diverse Cohorts
# metadata. There are some missing values in this data set that exist in 1.0 or
# Diverse Cohorts metadata, so we pull those values in.

mc_brad <- studies$mc_brad
meta_file <- synapse_download(mc_brad$metadata_id)
meta <- read.csv(meta_file$path)

if (verbose) {
  cat("\n", mc_brad$name, "\n")
  print(colnames(meta))
  print_qc(meta, spec,
           column_renames = list(
             PMI = "pmi",
             isHispanic = "ethnicity",
             amyCerad = "CERAD",
             amyThal = "Thal"
           )
  )
}

meta_new <- harmonize(mc_brad$name, meta, spec, harmonized_baseline) |>
  select(-study)

if (verbose) {
  print_qc(meta_new, spec)
}

cat("\n", mc_brad$name, "\n")
validate_values(meta_new, spec)

new_filename <- write_metadata(meta_new, meta_file$name)
new_syn_id <- synapse_upload(new_filename, upload_id)


# MC_snRNA ---------------------------------------------------------------------

# Has some sample overlap with AMP-AD 1.0 Mayo metadata and Diverse Cohorts
# metadata. After harmonization we pull in any missing values from 1.0 and
# Diverse Cohorts metadata.

mc_snrna <- studies$mc_snrna
meta_file <- synapse_download(mc_snrna$metadata_id)
meta <- read.csv(meta_file$path)

if (verbose) {
  cat("\n", mc_snrna$name, "\n")
  print(colnames(meta))
  print_qc(meta, spec,
           column_renames = list(
             PMI = "pmi",
             isHispanic = "ethnicity",
             amyCerad = "CERAD"
           )
  )
}

meta_new <- harmonize(mc_snrna$name, meta, spec, harmonized_baseline) |>
  select(-study)

if (verbose) {
  print_qc(meta_new, spec)
}

cat("\n", mc_snrna$name, "\n")
validate_values(meta_new, spec)

new_filename <- write_metadata(meta_new, meta_file$name)
new_syn_id <- synapse_upload(new_filename, upload_id)


# MCMPS ------------------------------------------------------------------------

# Note: Samples come from Mayo Clinic but there is no overlap with AMP-AD 1.0 or
# Diverse Cohorts data.

mcmps <- studies$mcmps
meta_file <- synapse_download(mcmps$metadata_id)
meta <- read.csv(meta_file$path)

if (verbose) {
  cat("\n", mcmps$name, "\n")
  print(colnames(meta))
  print_qc(meta, spec,
           column_renames = list(
             PMI = "pmi",
             isHispanic = "ethnicity",
             amyCerad = "CERAD"
           )
  )
}

meta_new <- harmonize(mcmps$name, meta, spec) |>
  select(-study)

if (verbose) {
  print_qc(meta_new, spec)
}

cat("\n", mcmps$name, "\n")
validate_values(meta_new, spec)

new_filename <- write_metadata(meta_new, meta_file$name)
new_syn_id <- synapse_upload(new_filename, upload_id)


# SEA-AD -----------------------------------------------------------------------

# The version of SEA-AD that is on Synapse is missing Hispanic/Latino
# information that is present in the version released by the Allen Institute on
# brain-map.org. We use the version on Synapse but pull in the missing
# information from the Allen Institute version.

sea_ad <- studies$sea_ad
meta_file <- synapse_download(sea_ad$metadata_id)

sea_ad_file <- file.path("data", "downloads", basename(sea_ad$extra_metadata))
download.file(sea_ad$extra_metadata, destfile = sea_ad_file)

meta <- read.csv(meta_file$path, row.names = 1)
meta_sea_ad <- read_xlsx(sea_ad_file)

if (verbose) {
  cat("\n", sea_ad$name, "\n")
  print(colnames(meta))
  print(colnames(meta_sea_ad))

  print_qc(meta, spec,
           column_renames = list(
             PMI = "pmi",
             amyCerad = "CERAD",
             amyThal = "Thal.phase"
           )
  )
  print_qc(meta_sea_ad, spec,
           column_renames = list(isHispanic = "Hispanic/Latino"))
}

meta_new <- harmonize(sea_ad$name, meta, spec,
                      extra_metadata = meta_sea_ad) |>
  select(-study)

if (verbose) {
  print_qc(meta_new, spec)
}

cat("\n", sea_ad$name, "\n")
validate_values(meta_new, spec)

new_filename <- write_metadata(meta_new, meta_file$name)
new_syn_id <- synapse_upload(new_filename, upload_id)


# SMIB-AD ----------------------------------------------------------------------
# No overlap with other data sets.

smib_ad <- studies$smib_ad
meta_file <- synapse_download(smib_ad$metadata_id)
meta <- read.csv(meta_file$path)

if (verbose) {
  cat("\n", smib_ad$name, "\n")
  print(colnames(meta))
  print_qc(meta, spec,
           column_renames = list(
             PMI = "pmi",
             isHispanic = "ethnicity",
             amyCerad = "CERAD"
           )
  )
}

meta_new <- harmonize(smib_ad$name, meta, spec) |>
  select(-study)

if (verbose) {
  print_qc(meta_new, spec)
}

cat("\n", smib_ad$name, "\n")
validate_values(meta_new, spec)

new_filename <- write_metadata(meta_new, meta_file$name)
new_syn_id <- synapse_upload(new_filename, upload_id)
